import React, { useState, useMemo } from "react";
import { useLanguage } from "../../../../contexts";
import { useGetPrescriptionsQuery } from "../../../../services/api/prescriptionsApi";
import html2pdf from 'html2pdf.js';

export function MonitoringSection() {
  const { t } = useLanguage();
  
  // Use RTK Query to fetch prescriptions which includes the reports history
  const { data: prescriptions, isLoading, error } = useGetPrescriptionsQuery(undefined, {
    pollingInterval: 30000, // Auto-refresh monitoring feed
    refetchOnMountOrArgChange: true
  });

  const [selectedReport, setSelectedReport] = useState(null);

  const allReports = useMemo(() => {
    if (!prescriptions) return [];
    // Flatten all reports from all prescriptions and attach patient info
    return prescriptions.flatMap(prescription => 
      (prescription.reports || []).map(report => ({
        ...report,
        patientName: prescription.patient?.full_name || 'Unknown Patient',
        patientEmail: prescription.patient?.email,
        prescriptionTitle: prescription.exercises?.map(e => e.name).join(', ') || 'Prescription',
      }))
    ).sort((a, b) => new Date(b.created_at) - new Date(a.created_at));
  }, [prescriptions]);

  const handleDownloadReport = (report) => {
    const content = report.html_report || report.report;
    if (!content) return;
    
    const element = document.createElement('div');
    element.innerHTML = `
      <div style="padding: 40px; font-family: sans-serif; color: #333;">
        <h1 style="color: #2c3e50; text-align: center; margin-bottom: 30px; border-bottom: 2px solid #eee; padding-bottom: 10px;">Session Report</h1>
        <div style="margin-bottom: 20px; color: #666;">
          <p><strong>Patient:</strong> ${report.patientName}</p>
          <p><strong>Date:</strong> ${new Date(report.created_at).toLocaleString()}</p>
        </div>
        <div class="report-content">
          ${content}
        </div>
        <div style="margin-top: 40px; text-align: center; font-size: 12px; color: #888;">
          Generated by Healify
        </div>
      </div>
    `;
    
    const opt = {
      margin: 0.5,
      filename: `report-${report.patientName.replace(/\s+/g, '-').toLowerCase()}-${new Date(report.created_at).toISOString().split('T')[0]}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
    };
    
    html2pdf().set(opt).from(element).save();
  };

  return (
    <div className="flex flex-col lg:flex-row gap-6 h-[calc(100vh-140px)]">
      {/* Left Panel: List */}
      <div className="flex-1 flex flex-col min-w-0">
        <div className="shrink-0 p-6 border-b border-gray-100 dark:border-slate-700 bg-white dark:bg-slate-800 rounded-t-2xl">
          <h2 className="text-xl font-bold text-text-primary dark:text-cyan-300">
            {t('therapistDashboard.monitoring.title') || 'Patient Monitoring'}
          </h2>
          <p className="text-sm text-text-muted dark:text-slate-400 mt-1">
            Real-time session updates from all your patients
          </p>
        </div>

        <div className="flex-1 overflow-y-auto p-4 custom-scrollbar bg-gray-50/50 dark:bg-slate-900/50 rounded-b-2xl border border-gray-100 dark:border-slate-700 border-t-0 space-y-4">
          {isLoading ? (
            <div className="text-center py-10">
               <svg className="animate-spin h-8 w-8 text-primary mx-auto mb-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
               </svg>
               <p className="text-text-muted">Loading monitoring data...</p>
            </div>
          ) : error ? (
            <div className="text-center py-10 text-red-500">
              <p>{error}</p>
            </div>
          ) : allReports.length === 0 ? (
             <div className="text-center py-10 text-text-muted">
               <p>No sessions recorded yet.</p>
             </div>
          ) : (
            allReports.map((report, idx) => {
              let analysis = {};
              try {
                analysis = typeof report.analysis_data === 'string' ? JSON.parse(report.analysis_data) : report.analysis_data || {};
              } catch (e) { console.error("Error parsing analysis data", e); }

              // Extract Exercise Names
              let exerciseName = "Therapy Session";
              if (analysis.exercises_detail && Array.isArray(analysis.exercises_detail) && analysis.exercises_detail.length > 0) {
                 exerciseName = analysis.exercises_detail.map(e => e.name || e.exercise).filter(Boolean).join(", ");
              } else if (analysis.exercises_completed && Array.isArray(analysis.exercises_completed)) {
                 exerciseName = analysis.exercises_completed.join(", ");
              } else if (analysis.exercise_name) {
                 exerciseName = analysis.exercise_name;
              }

              // Extract Total Reps
              let reps = "0";
              if (analysis.total_reps !== undefined) {
                 reps = analysis.total_reps;
              } else if (analysis.reps_completed !== undefined) {
                 reps = analysis.reps_completed;
              } else if (analysis.exercises_detail && Array.isArray(analysis.exercises_detail)) {
                 reps = analysis.exercises_detail.reduce((sum, ex) => sum + (Number(ex.reps_completed) || 0), 0);
              }

              const accuracy = analysis.average_accuracy || 0;

              // Helper for accuracy color
              const getAccuracyColor = (acc) => {
                if (acc >= 90) return "text-green-600 dark:text-green-400";
                if (acc >= 75) return "text-yellow-600 dark:text-yellow-400";
                return "text-red-600 dark:text-red-400";
              };

              return (
                <div 
                  key={report.id || idx}
                  className={`bg-white dark:bg-slate-800 rounded-xl shadow-md p-6 hover:shadow-lg transition border 
                    ${selectedReport?.id === report.id 
                      ? "border-primary dark:border-cyan-500 ring-1 ring-primary dark:ring-cyan-500" 
                      : "border-transparent dark:border-cyan-900"}`}
                >
                  <div className="flex items-start justify-between mb-4">
                    <div className="flex items-start gap-4">
                       <div className="w-12 h-12 rounded-lg flex items-center justify-center bg-blue-100 dark:bg-blue-900/40 text-blue-600 dark:text-blue-400 font-bold text-lg">
                          {report.patientName.substring(0, 2)}
                       </div>
                       
                       <div>
                          <h3 className="text-lg font-bold text-text-primary dark:text-cyan-300 mb-1">
                             {report.patientName}
                          </h3>
                          <div className="flex items-center gap-4 text-sm text-text-muted dark:text-slate-400">
                             <div className="flex items-center gap-1">
                                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                                </svg>
                                {new Date(report.created_at).toLocaleDateString()}
                             </div>
                             <div className="flex items-center gap-1">
                                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                                </svg>
                                {new Date(report.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                             </div>
                          </div>
                       </div>
                    </div>

                    <button 
                      onClick={(e) => {
                        e.stopPropagation();
                        setSelectedReport(selectedReport?.id === report.id ? null : report);
                      }}
                      className={`px-3 py-1.5 rounded-lg text-sm font-medium transition flex items-center gap-1.5
                        ${selectedReport?.id === report.id 
                          ? "bg-red-100 text-red-600 dark:bg-red-900/30 dark:text-red-400" 
                          : "bg-primary/10 text-primary dark:bg-cyan-900/30 dark:text-cyan-400 hover:bg-primary/20"}`}
                    >
                      <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                         <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                       </svg>
                      {selectedReport?.id === report.id ? "Close" : "Report"}
                    </button>
                  </div>

                  <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                     <div className="bg-gray-50 dark:bg-slate-700 rounded-lg p-3">
                        <p className="text-xs text-text-muted dark:text-slate-400 mb-1">Exercise</p>
                        <p className="font-bold text-text-primary dark:text-slate-200 truncate" title={exerciseName}>
                           {exerciseName}
                        </p>
                     </div>
                     <div className="bg-gray-50 dark:bg-slate-700 rounded-lg p-3">
                        <p className="text-xs text-text-muted dark:text-slate-400 mb-1">Start Reps</p>
                        <p className="font-bold text-text-primary dark:text-slate-200">{reps}</p>
                     </div>
                     <div className="bg-gray-50 dark:bg-slate-700 rounded-lg p-3">
                        <p className="text-xs text-text-muted dark:text-slate-400 mb-1">Accuracy</p>
                        <p className={`font-bold ${getAccuracyColor(accuracy)}`}>
                           {accuracy}%
                        </p>
                     </div>
                  </div>
                </div>
              );
            })
          )}
        </div>
      </div>

      {/* Right Panel: Report Details */}
      {selectedReport && (
        <div className="w-full lg:w-[750px] shrink-0 h-full">
           <div className="bg-white dark:bg-slate-800 rounded-xl shadow-xl border border-transparent dark:border-cyan-900 h-full flex flex-col animate-in slide-in-from-right-10 duration-300">
              {/* Header */}
              <div className="p-6 border-b dark:border-slate-700 bg-white dark:bg-slate-800 sticky top-0 z-10 flex justify-between items-start rounded-t-xl">
                 <div>
                    <h2 className="text-xl font-bold text-gray-900 dark:text-white">
                      Session Report
                    </h2>
                    <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
                      {selectedReport.patientName} • {new Date(selectedReport.created_at).toLocaleDateString()}
                    </p>
                 </div>
                 <div className="flex items-center gap-2">
                   <button
                     onClick={() => handleDownloadReport(selectedReport)}
                     className="p-2 text-primary hover:text-primary-dark dark:text-cyan-400 dark:hover:text-cyan-300 rounded-lg hover:bg-primary/10 dark:hover:bg-cyan-900/30 transition shadow-sm border border-transparent hover:border-primary/20 dark:hover:border-cyan-500/30"
                     title="Download PDF"
                   >
                      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                      </svg>
                   </button>
                   <button
                      onClick={() => setSelectedReport(null)}
                      className="p-2 text-gray-400 hover:text-gray-500 rounded-lg hover:bg-gray-100 dark:hover:bg-slate-700 transition"
                    >
                      <span className="sr-only">Close panel</span>
                      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                      </svg>
                   </button>
                 </div>
              </div>

              {/* Content */}
              <div className="p-6 overflow-y-auto flex-1 custom-scrollbar">
                 <div className="prose prose-sm max-w-none dark:prose-invert">
                    <div className="mb-6 p-4 bg-gray-50 dark:bg-slate-700/50 rounded-lg">
                       <h3 className="text-sm font-semibold uppercase tracking-wider text-gray-500 dark:text-gray-400 mb-2 mt-0">Primary Exercise</h3>
                       <p className="mb-0 text-gray-900 dark:text-gray-200 font-medium">
                         {(() => {
                           try {
                             const a = typeof selectedReport.analysis_data === 'string' ? JSON.parse(selectedReport.analysis_data) : selectedReport.analysis_data;
                             return a?.exercises_detail?.[0]?.name || a?.exercise_name || "Therapy Session";
                           } catch (e) { return "Therapy Session"; }
                         })()}
                       </p>
                    </div>

                    <div dangerouslySetInnerHTML={{ 
                      __html: selectedReport.html_report || selectedReport.report || "<div class='text-center text-gray-500'>No detailed HTML report available.</div>" 
                    }} />
                 </div>
              </div>
           </div>
        </div>
      )}
    </div>
  );
}
