import React, { useState, useMemo } from "react";
import { useLanguage } from "../../../contexts";
import { useAuth } from "../../../contexts/AuthContext";
import { useToast, LoadingSpinner } from "../../../components/ui";
import { useGetPatientHistoryQuery } from "../../../services/api/prescriptionsApi";
import html2pdf from 'html2pdf.js';

export default function SessionHistorySection() {
  const { t } = useLanguage();
  const { user } = useAuth();
  const toast = useToast();
  
  const { data: prescriptions, isLoading, error: apiError } = useGetPatientHistoryQuery(user?.id, {
    skip: !user
  });
  
  const [filterExercise, setFilterExercise] = useState("all");
  const [selectedSession, setSelectedSession] = useState(null);
console.log('selectedSession', selectedSession);
  const sessions = useMemo(() => {
    if (!prescriptions) return [];

    const allReports = prescriptions.flatMap(prescription => {
      return (prescription.reports || []).map(report => {
       
        // Safe extraction of analysis data
        let analysis = {};
        try {
          analysis = typeof report.analysis_data === 'string' 
            ? JSON.parse(report.analysis_data) 
            : report.analysis_data || {};
        } catch (e) {
          console.warn("Failed to parse analysis data", e);
        }

        let exerciseNames = "Daily Session";
        if (analysis.exercises_detail && Array.isArray(analysis.exercises_detail) && analysis.exercises_detail.length > 0) {
          exerciseNames = analysis.exercises_detail.map(ex => ex.exercise).join(", ");
        } else if (analysis.exercises_completed > 0) {
          exerciseNames = `${analysis.exercises_completed} Exercises Completed`;
        }

        return {
          id: report.id,
          prescriptionId: prescription.id,
          date: report.created_at,
          time: new Date(report.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
          exercise: exerciseNames, 
          duration: analysis.duration_minutes || 0,
          reps: analysis.total_reps || 0,
          sets: analysis.exercises_completed || 0,
          accuracy: analysis.average_accuracy || 0,
          painLevel: analysis.pain_level || 0, // Assuming this might be added later
          status: "completed", // If report exists, it's considered completed/attempted
          notes: analysis.patient_notes || "",
          improvements: analysis.improvements || [],
          html_report: report.html_report || report.html_data || report.report || (analysis && analysis.html_data) || "",
          raw: report
        };
      });
    });

    // Sort by date descending (newest first)
    return allReports.sort((a, b) => 
      new Date(b.date) - new Date(a.date)
    );
  }, [prescriptions]);

  // Derive exercise types from the flattened data (though currently we name them "Daily Session")
  // If analysis_data contains specific exercise names, we could map them. 
  // For now, filtering might be less relevant if they are all "Daily Session", 
  // but we keep the logic for future extensibility.
  const exerciseTypes = ["all", ...new Set(sessions.map(s => s.exercise))];

  const filteredSessions = sessions.filter(session =>
    filterExercise === "all" || session.exercise === filterExercise
  );

  const getAccuracyColor = (accuracy) => {
    if (accuracy >= 90) return "text-green-600";
    if (accuracy >= 75) return "text-yellow-600";
    return "text-red-600";
  };

  const getPainColor = (level) => {
    if (level <= 2) return "text-green-600";
    if (level <= 4) return "text-yellow-600";
    return "text-red-600";
  };

  if (isLoading) {
    return (
      <div className="flex h-64 items-center justify-center">
        <LoadingSpinner size="lg" />
      </div>
    );
  }

  if (apiError) {
    return (
      <div className="p-8 text-center text-red-500">
        <p>{apiError?.data?.message || "Failed to load history"}</p>
        <button 
          onClick={() => window.location.reload()} 
          className="mt-4 text-blue-500 hover:underline"
        >
          Retry
        </button>
      </div>
    );
  }

  const handleDownloadReport = (htmlContent) => {
    if (!htmlContent) return;
    
    const element = document.createElement('div');
    element.innerHTML = `
      <div style="padding: 40px; font-family: sans-serif; color: #333;">
        <h1 style="color: #2c3e50; text-align: center; margin-bottom: 30px; border-bottom: 2px solid #eee; padding-bottom: 10px;">Session Report</h1>
        <div class="report-content">
          ${htmlContent}
        </div>
        <div style="margin-top: 40px; text-align: center; font-size: 12px; color: #888;">
          Generated by Healify
        </div>
      </div>
    `;
    
    const opt = {
      margin: 0.5,
      filename: `session-report-${new Date().toISOString().split('T')[0]}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
    };
    
    html2pdf().set(opt).from(element).save();
  };

  return (
    <div className="flex flex-col lg:flex-row gap-6 h-[calc(100vh-100px)]">
      {/* Left Side: Header, Stats, and List */}
      <div className="flex-1 flex flex-col min-w-0">
        {/* Fixed Header & Stats Area */}
        <div className="shrink-0 space-y-6 mb-4">
          <div>
            <div className="flex justify-between items-center">
              <div>
                <p className="text-text-muted dark:text-slate-300 mt-1">{t('patientDashboard.history.subtitle')}</p>
              </div>

              <button
                onClick={() => toast.success("Exercise history exported successfully! Check your downloads folder.")}
                className="px-6 py-3 bg-primary text-white font-semibold rounded-lg hover:bg-primary-dark transition flex items-center gap-2">
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
                {t('patientDashboard.history.exportHistory')}
              </button>
            </div>
          </div>

          {sessions.length > 0 && (
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <div className="bg-white dark:bg-slate-800 rounded-xl shadow-md p-6 border border-transparent dark:border-cyan-900">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-text-muted dark:text-slate-400 text-sm mb-1">{t('patientDashboard.history.totalSessions')}</p>
                    <p className="text-3xl font-bold text-text-primary dark:text-cyan-300">{sessions.length}</p>
                  </div>
                  <div className="w-12 h-12 bg-primary/10 dark:bg-cyan-900/40 rounded-lg flex items-center justify-center">
                    <svg className="w-6 h-6 text-primary dark:text-cyan-300" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
                    </svg>
                  </div>
                </div>
              </div>

              <div className="bg-white dark:bg-slate-800 rounded-xl shadow-md p-6 border border-transparent dark:border-cyan-900">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-text-muted dark:text-slate-400 text-sm mb-1">{t('patientDashboard.history.completed')}</p>
                    <p className="text-3xl font-bold text-green-600 dark:text-green-400">
                      {sessions.length}
                    </p>
                  </div>
                  <div className="w-12 h-12 bg-green-100 dark:bg-green-900/40 rounded-lg flex items-center justify-center">
                    <svg className="w-6 h-6 text-green-600 dark:text-green-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                  </div>
                </div>
              </div>

              <div className="bg-white dark:bg-slate-800 rounded-xl shadow-md p-6 border border-transparent dark:border-cyan-900">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-text-muted dark:text-slate-400 text-sm mb-1">{t('patientDashboard.history.avgAccuracy')}</p>
                    <p className="text-3xl font-bold text-text-primary dark:text-cyan-300">
                      {Math.round(sessions.reduce((acc, s) => acc + s.accuracy, 0) / (sessions.filter(s => s.accuracy > 0).length || 1))}%
                    </p>
                  </div>
                  <div className="w-12 h-12 bg-purple-100 dark:bg-purple-900/40 rounded-lg flex items-center justify-center">
                    <svg className="w-6 h-6 text-purple-600 dark:text-purple-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" />
                    </svg>
                  </div>
                </div>
              </div>

              <div className="bg-white dark:bg-slate-800 rounded-xl shadow-md p-6 border border-transparent dark:border-cyan-900">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-text-muted dark:text-slate-400 text-sm mb-1">{t('patientDashboard.history.totalTime')}</p>
                    <p className="text-3xl font-bold text-text-primary dark:text-cyan-300">
                      {Math.round(sessions.reduce((acc, s) => acc + (s.duration || 0), 0) / 60)}h
                    </p>
                  </div>
                  <div className="w-12 h-12 bg-blue-100 dark:bg-blue-900/40 rounded-lg flex items-center justify-center">
                    <svg className="w-6 h-6 text-blue-600 dark:text-blue-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                  </div>
                </div>
              </div>
            </div>
          )}

          {exerciseTypes.length > 1 && (
            <div className="bg-white dark:bg-slate-800 rounded-xl shadow-md p-4 border border-transparent dark:border-cyan-900">
              <div className="flex items-center gap-4">
                <span className="text-sm font-medium text-text-primary dark:text-slate-200">{t('patientDashboard.history.filterByExercise')}</span>
                <div className="flex flex-wrap gap-2">
                  {exerciseTypes.map((exercise) => (
                    <button
                      key={exercise}
                      onClick={() => setFilterExercise(exercise)}
                      className={`px-4 py-2 rounded-lg font-medium text-sm transition ${
                        filterExercise === exercise
                          ? "bg-primary text-white"
                          : "bg-gray-100 dark:bg-slate-700 text-gray-700 dark:text-slate-300 hover:bg-gray-200 dark:hover:bg-slate-600"
                      }`}
                    >
                      {exercise === "all" ? t('patientDashboard.history.allExercises') : exercise}
                    </button>
                  ))}
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Scrollable List Area */}
        <div className="flex-1 overflow-y-auto pr-2 custom-scrollbar space-y-4">
          {filteredSessions.map((session) => (
            <div
              key={session.id}
              className={`bg-white dark:bg-slate-800 rounded-xl shadow-md p-6 hover:shadow-lg transition border 
                ${selectedSession?.id === session.id 
                  ? "border-primary dark:border-cyan-500 ring-1 ring-primary dark:ring-cyan-500" 
                  : "border-transparent dark:border-cyan-900"}`}
            >
              <div className="flex items-start justify-between mb-4">
                <div className="flex items-start gap-4">
                  <div className={`w-12 h-12 rounded-lg flex items-center justify-center bg-green-100 dark:bg-green-900/40`}>
                    <svg className="w-6 h-6 text-green-600 dark:text-green-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                  </div>

                  <div>
                    <h3 className="text-lg font-bold text-text-primary dark:text-cyan-300 mb-1">
                      {session.exercise} <span className="text-sm font-normal text-gray-500">#{session.id}</span>
                    </h3>
                    <div className="flex items-center gap-4 text-sm text-text-muted dark:text-slate-400">
                      <div className="flex items-center gap-1">
                        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                        </svg>
                        {new Date(session.date).toLocaleDateString()}
                      </div>
                      <div className="flex items-center gap-1">
                        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                        {session.time}
                      </div>
                    </div>
                  </div>
                </div>

                <button 
                  onClick={(e) => {
                    e.stopPropagation();
                    setSelectedSession(selectedSession?.id === session.id ? null : session);
                  }}
                  className={`px-3 py-1.5 rounded-lg text-sm font-medium transition flex items-center gap-1.5
                    ${selectedSession?.id === session.id 
                      ? "bg-red-100 text-red-600 dark:bg-red-900/30 dark:text-red-400" 
                      : "bg-primary/10 text-primary dark:bg-cyan-900/30 dark:text-cyan-400 hover:bg-primary/20"}`}
                >
                  <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                     <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                   </svg>
                  {selectedSession?.id === session.id ? "Close" : "Report"}
                </button>
              </div>

              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                <div className="bg-gray-50 dark:bg-slate-700 rounded-lg p-3">
                  <p className="text-xs text-text-muted dark:text-slate-400 mb-1">{t('patientDashboard.history.accuracy')}</p>
                  <p className={`text-lg font-bold ${getAccuracyColor(session.accuracy)}`}>
                    {session.accuracy}%
                  </p>
                </div>
                {session.duration > 0 && (
                  <div className="bg-gray-50 dark:bg-slate-700 rounded-lg p-3">
                    <p className="text-xs text-text-muted dark:text-slate-400 mb-1">{t('patientDashboard.history.duration')}</p>
                    <p className="text-lg font-bold text-text-primary dark:text-slate-200">{session.duration} min</p>
                  </div>
                )}
                {session.sets > 0 && (
                  <div className="bg-gray-50 dark:bg-slate-700 rounded-lg p-3">
                    <p className="text-xs text-text-muted dark:text-slate-400 mb-1">Exercises</p>
                    <p className="text-lg font-bold text-text-primary dark:text-slate-200">{session.sets}</p>
                  </div>
                )}
                {session.reps > 0 && (
                  <div className="bg-gray-50 dark:bg-slate-700 rounded-lg p-3">
                    <p className="text-xs text-text-muted dark:text-slate-400 mb-1">Total Reps</p>
                    <p className="text-lg font-bold text-text-primary dark:text-slate-200">{session.reps}</p>
                  </div>
                )}
              </div>
            </div>
          ))}

          {filteredSessions.length === 0 && (
            <div className="bg-white dark:bg-slate-800 rounded-xl shadow-md p-12 text-center border border-transparent dark:border-cyan-900">
              <svg className="w-16 h-16 text-gray-300 dark:text-slate-600 mx-auto mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
              </svg>
              <p className="text-text-muted dark:text-slate-400 text-lg">No sessions found in history</p>
            </div>
          )}
        </div>
      </div>

      {/* Right Side: Report Details Panel */}
      {selectedSession && (
        <div className="w-full lg:w-[750px] shrink-0 h-full">
           <div className="bg-white dark:bg-slate-800 rounded-xl shadow-xl border border-transparent dark:border-cyan-900 h-full flex flex-col">
              {/* Header */}
              <div className="p-6 border-b dark:border-slate-700 bg-white dark:bg-slate-800 sticky top-0 z-10 flex justify-between items-start rounded-t-xl">
                 <div>
                    <h2 className="text-xl font-bold text-gray-900 dark:text-white">
                      Session Report
                    </h2>
                    <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
                      {new Date(selectedSession.date).toLocaleDateString()} at {selectedSession.time}
                    </p>
                 </div>
                 <div className="flex items-center gap-2">
                   {selectedSession.html_report && (
                     <button
                       onClick={() => handleDownloadReport(selectedSession.html_report)}
                       className="p-2 text-primary hover:text-primary-dark dark:text-cyan-400 dark:hover:text-cyan-300 rounded-lg hover:bg-primary/10 dark:hover:bg-cyan-900/30 transition shadow-sm border border-transparent hover:border-primary/20 dark:hover:border-cyan-500/30"
                       title="Download PDF"
                     >
                        <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                        </svg>
                     </button>
                   )}
                   <button
                      onClick={() => setSelectedSession(null)}
                      className="p-2 text-gray-400 hover:text-gray-500 rounded-lg hover:bg-gray-100 dark:hover:bg-slate-700 transition"
                    >
                      <span className="sr-only">Close panel</span>
                      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                      </svg>
                   </button>
                 </div>
              </div>

              {/* Content */}
              <div className="p-6 overflow-y-auto flex-1 custom-scrollbar">
                 <div className="prose prose-sm max-w-none dark:prose-invert">
                    {/* Exercises Summary */}
                    <div className="mb-6 p-4 bg-gray-50 dark:bg-slate-700/50 rounded-lg">
                       <h3 className="text-sm font-semibold uppercase tracking-wider text-gray-500 dark:text-gray-400 mb-2 mt-0">Exercises</h3>
                       <p className="mb-0 text-gray-900 dark:text-gray-200 font-medium">{selectedSession.exercise}</p>
                    </div>

                    {selectedSession.html_report ? (
                       <div dangerouslySetInnerHTML={{ __html: selectedSession.html_report }} />
                    ) : (
                       <div className="text-center p-8 bg-gray-50 dark:bg-slate-700/50 rounded-xl">
                          <p className="text-text-muted dark:text-slate-400">No detailed report available.</p>
                       </div>
                    )}
                 </div>
              </div>
           </div>
        </div>
      )}
    </div>
  );
}

